# Generated by Django 5.1.4 on 2025-01-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cm_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='exam_sn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='exam_sr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='td_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='tp_completed',
            field=models.IntegerField(default=0),
        ),
    ]
