# Generated by Django 5.1.4 on 2025-01-19 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_course_cm_completed_course_exam_sn_course_exam_sr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseassignment',
            name='custom_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.course'),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.professor'),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.room'),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='type',
            field=models.CharField(choices=[('CM', 'Cours Magistral'), ('TD', 'Travaux Dirigés'), ('TP', 'Travaux Pratiques'), ('DV', 'DV'), ('EXAM', 'Exam'), ('CUSTOM', 'Custom Text')], max_length=10),
        ),
    ]
